language: csharp

sudo: false  # use the new container-based Travis infrastructure

script: 
  - ./build.sh All

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a43d3bdbdee36cd658ea
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false