//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HomagGroup.ResourceHelper;


namespace TestTemplatesCSharp.Properties {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("HomagGroup.ResourceHelperGenerator", "1.1.6")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class ResourcesKeys {
        
        /// <summary>
        ///   Looks up a localized string similar to: Message: '{0}'
        /// </summary>
        /// <summary>
        ///   Provides access to string resource key of value similar to: Message: '{0}'
        /// </summary>
        public static HomagGroup.ResourceHelper.ResourceIdentifier TestMessage(object arg0) {
            return HomagGroup.ResourceHelper.ResourceIdentifier.Create(typeof(Resources), "TestMessage", arg0);
        }
    }
}
