//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIT.Tools.VisualStudioTextTransform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIT.Tools.VisualStudioTextTransform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Error: {0}.
        /// </summary>
        internal static string Program_Main_ {
            get {
                return ResourceManager.GetString("Program_Main_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application crashed with: {0}.
        /// </summary>
        internal static string Program_Main_Application_crashed_with___0_ {
            get {
                return ResourceManager.GetString("Program_Main_Application_crashed_with___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating VS instance....
        /// </summary>
        internal static string Program_Main_Creating_VS_instance___ {
            get {
                return ResourceManager.GetString("Program_Main_Creating_VS_instance___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything worked!.
        /// </summary>
        internal static string Program_Main_Everything_worked_ {
            get {
                return ResourceManager.GetString("Program_Main_Everything_worked_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED to process &quot;{0}&quot;.
        /// </summary>
        internal static string Program_Main_FAILED_to_process___0__ {
            get {
                return ResourceManager.GetString("Program_Main_FAILED_to_process___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding and processing all TextTransform templates....
        /// </summary>
        internal static string Program_Main_Finding_and_processing___tt_templates___ {
            get {
                return ResourceManager.GetString("Program_Main_Finding_and_processing___tt_templates___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening {0}.
        /// </summary>
        internal static string Program_Main_Opening__0_ {
            get {
                return ResourceManager.GetString("Program_Main_Opening__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the file path &quot;{0}&quot; is either invalid or doesn&apos;t exist!.
        /// </summary>
        internal static string Program_Main_the_file_path___0___is_either_invalid_or_doesn_t_exist_ {
            get {
                return ResourceManager.GetString("Program_Main_the_file_path___0___is_either_invalid_or_doesn_t_exist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must provide a solution file.
        /// </summary>
        internal static string Program_Main_you_must_provide_a_solution_file {
            get {
                return ResourceManager.GetString("Program_Main_you_must_provide_a_solution_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &quot;{0}&quot;....
        /// </summary>
        internal static string Program_ProcessTemplate_Processing___0_____ {
            get {
                return ResourceManager.GetString("Program_ProcessTemplate_Processing___0_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is null or empty or file doesn&apos;t exist..
        /// </summary>
        internal static string Program_ProcessTemplateInMemory_String_is_null_or_empty_or_file_doesn_t_exist_ {
            get {
                return ResourceManager.GetString("Program_ProcessTemplateInMemory_String_is_null_or_empty_or_file_doesn_t_exist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning DTE instance..
        /// </summary>
        internal static string VisualStudioTextTemplateHost_GetService_Returning_DTE_instance_ {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_GetService_Returning_DTE_instance_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service request of type: {0}.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_GetService_Service_request_of_type___0_ {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_GetService_Service_request_of_type___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not load Assembly: {0}.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolveAssemblyReference_Error__Could_not_load_Assembly___0_ {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolveAssemblyReference_Error__Could_not_load_Assem" +
                        "bly___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we could load the given assembly but cannot resolve it to a path..
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolveAssemblyReference_we_could_load_the_given_assembly_but_cannot_resolve_it_to_a_path_ {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolveAssemblyReference_we_could_load_the_given_ass" +
                        "embly_but_cannot_resolve_it_to_a_path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Directive is unknown!.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolveDirectiveProcessor_Processor_Directive_is_unknown_ {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolveDirectiveProcessor_Processor_Directive_is_unk" +
                        "nown_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the directiveId cannot be null.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolveParameterValue_the_directiveId_cannot_be_null {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolveParameterValue_the_directiveId_cannot_be_null" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the parameterName cannot be null.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolveParameterValue_the_parameterName_cannot_be_null {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolveParameterValue_the_parameterName_cannot_be_nu" +
                        "ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the processorName cannot be null.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolveParameterValue_the_processorName_cannot_be_null {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolveParameterValue_the_processorName_cannot_be_nu" +
                        "ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the file name cannot be null.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolvePath_the_file_name_cannot_be_null {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolvePath_the_file_name_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found {0}.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolvePathPrivate_found__0_ {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolvePathPrivate_found__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resolving {0}.
        /// </summary>
        internal static string VisualStudioTextTemplateHost_ResolvePathPrivate_resolving__0_ {
            get {
                return ResourceManager.GetString("VisualStudioTextTemplateHost_ResolvePathPrivate_resolving__0_", resourceCulture);
            }
        }
    }
}
